- name: Ensure sshd privilege separation directory exists
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    mode: "0755"

- name: Deactivate authentification by password
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH service

- name: Ban login via root account
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH service
